parameters:
#    kaymorey_portfolio.example.class: Kaymorey\PortfolioBundle\Example

services:
#    kaymorey_portfolio.example:
#        class: %kaymorey_portfolio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
