<?php

namespace Kaymorey\PortfolioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocRepository extends EntityRepository
{
}
